"""Added url table

Revision ID: 35b23a190052
Revises: 
Create Date: 2022-04-04 00:42:53.520935

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35b23a190052"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_url", sa.String(length=200), nullable=False),
        sa.Column("short_path", sa.String(length=50), nullable=False),
        sa.Column("time_start", sa.DateTime(), nullable=False),
        sa.Column("time_end", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_path"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    # ### end Alembic commands ###
